### ISSUE TITLE
Failed to load plugin in FL Studio 11

### ISSUE THREAD

**Issue by Scrooge20291224** [fukuroder/fl_vstgui_sample#1]
After scanning, this VST plugin is labled with red font in the plugin list.
![image](https://user-images.githubusercontent.com/10172485/59069371-7862a900-88e9-11e9-8184-113dce8d13f2.png)
When using this plugin, the error reported:
![image](https://user-images.githubusercontent.com/10172485/59069391-8ca6a600-88e9-11e9-8df2-65ecf5d1bc56.png)
This VST plugin is store in the the path below:
![image](https://user-images.githubusercontent.com/10172485/59069438-ad6efb80-88e9-11e9-9632-6854e9a1bfc6.png)
And the path of VST plugin configured in FL Studio is:
![image](https://user-images.githubusercontent.com/10172485/59069478-cf687e00-88e9-11e9-9b80-1312eaf8c20d.png)
I will check codes for further info, if you can provide some experience beforehand, I will appreciate it.

**Comment by fukuroder** [comment]
Please place
C:\Program Files (x86)\Image-Line\FL Studio 20\Plugins\Fruity\Effects\sample\sample.dll

**Comment by Scrooge20291224** [comment]
> Please place
> C:\Program Files (x86)\Image-Line\FL Studio 20\Plugins\Fruity\Effects\sample\sample.dll

I will test it this afternoon, Thx

**Comment by Scrooge20291224** [comment]
It works,Thank you!
