### ISSUE TITLE
EditorWindow turns black when overlayed by Mixer

### ISSUE THREAD

**Issue by DominikStarke** [fukuroder/fl_vstgui_sample#2]
Hi,
thanks for example. It is really helpful.

I found an issue on Windows, that causes the editors ui to turn completely black if it is overlaid by the FL Studio Mixer (or sometimes the channel rack).
There is a workaround for this:

```
	if (ID == FPD_SetFocus)
	{
		HWND hwnd = _editor->getHWND();
		// UpdateWindow(hwnd);
		InvalidateRect(hwnd , NULL, TRUE);
	}
```

This will basically force a redraw when the plugin looses / gets focus.

However this feels like a hack. Is there a different way to resolve this?

Edit: Actually calling InvalidateRect is enough.

**Comment by fukuroder** [comment]
Thanks. I will fix this bug in a few days. Please wait a moment.

**Comment by fukuroder** [comment]
It will take time to resolve. Sorry.

**Comment by fukuroder** [comment]
Improved using the latest "develop" branch of VSTGUI.
